import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Info, Zap, ShieldCheck, Globe, Cpu, Version } from "lucide-react";

export default function About() {
  const appVersion = "1.0.0";

  return (
    <div className="space-y-8 max-w-4xl animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-4xl font-extrabold tracking-tight text-foreground lg:text-5xl">
            About K.Electrical <span className="text-primary italic">PMS</span>
          </h1>
          <p className="text-xl text-muted-foreground mt-2">
            The next-generation document ecosystem for electrical engineering.
          </p>
        </div>
        <Badge variant="secondary" className="px-4 py-1 text-md font-mono bg-secondary/20 border-secondary/50 text-secondary-foreground">
          Version {appVersion}
        </Badge>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="border-l-4 border-l-primary shadow-soft hover:shadow-card transition-shadow duration-300">
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="p-2 bg-primary/10 rounded-lg">
                <Cpu className="h-6 w-6 text-primary" />
              </div>
              <CardTitle>The Mission</CardTitle>
            </div>
          </CardHeader>
          <CardContent className="text-muted-foreground leading-relaxed">
            K.Electrical PMS was engineered to bridge the gap between complex electrical site work and professional corporate documentation. Our mission is to empower engineers to generate high-fidelity Invoices, Quotations, and Project reports instantly, anywhere in the world.
          </CardContent>
        </Card>

        <Card className="border-l-4 border-l-secondary shadow-soft hover:shadow-card transition-shadow duration-300">
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="p-2 bg-secondary/10 rounded-lg">
                <ShieldCheck className="h-6 w-6 text-secondary" />
              </div>
              <CardTitle>Enterprise Sync</CardTitle>
            </div>
          </CardHeader>
          <CardContent className="text-muted-foreground leading-relaxed">
            Built on a hybrid cloud-local architecture. Whether you are in a remote basement with no signal or a high-rise office, your data is always safe. The Global Sync Engine automatically pushes your offline work to the secure Supabase cloud the moment you reconnect.
          </CardContent>
        </Card>
      </div>

      <Card className="bg-gradient-to-br from-primary/5 to-secondary/5 border-none shadow-elevated">
        <CardHeader>
          <CardTitle>Our Documentation Standard</CardTitle>
          <CardDescription>Why we pride ourselves on precision</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-foreground/80 leading-relaxed">
            Every document generated by K.Electrical follows strict professional engineering standards. From automated labor cost calculations to dynamic VAT/Tax adjustments, we ensure your client-facing documents look elite, professional, and mathematically perfect.
          </p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 pt-4">
            <div className="text-center p-3 bg-background/50 rounded-xl border">
              <div className="font-bold text-primary">A4 Optimized</div>
              <div className="text-[10px] text-muted-foreground">Print-Ready PDF</div>
            </div>
            <div className="text-center p-3 bg-background/50 rounded-xl border">
              <div className="font-bold text-primary">Cloud Vault</div>
              <div className="text-[10px] text-muted-foreground">Secure Persistence</div>
            </div>
            <div className="text-center p-3 bg-background/50 rounded-xl border">
              <div className="font-bold text-primary">Map Integrated</div>
              <div className="text-[10px] text-muted-foreground">Project Geolocation</div>
            </div>
            <div className="text-center p-3 bg-background/50 rounded-xl border">
              <div className="font-bold text-primary">Native Suite</div>
              <div className="text-[10px] text-muted-foreground">Windows & Android</div>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="pt-6 text-center text-xs text-muted-foreground">
        © 2026 K.Electrical Project Management System. All rights reserved. 
        <br />
        Built with high-frequency agentic intelligence.
      </div>
    </div>
  );
}
